# Generated by Django 5.1 on 2024-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=55)),
                ('LastName', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
