# Generated by Django 5.1 on 2024-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MyEmail', models.EmailField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='myform',
            old_name='LastName',
            new_name='PassWord',
        ),
    ]
