# Generated by Django 5.1 on 2024-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lastname_myemail_rename_lastname_myform_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myform',
            name='PassWord',
        ),
    ]
