# Generated by Django 5.1 on 2024-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mypassword_remove_myform_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lastname',
        ),
        migrations.DeleteModel(
            name='MyEmail',
        ),
        migrations.DeleteModel(
            name='Mypassword',
        ),
        migrations.AddField(
            model_name='myform',
            name='LastName',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='myform',
            name='MyEmail',
            field=models.EmailField(default='our string', max_length=55),
        ),
        migrations.AddField(
            model_name='myform',
            name='PassWord',
            field=models.CharField(default='my string', max_length=55),
        ),
        migrations.AlterField(
            model_name='myform',
            name='FirstName',
            field=models.CharField(max_length=200),
        ),
    ]
